# Generated by Django 3.1 on 2025-11-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20251107_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shippingaddress'),
        ),
    ]
