# Generated by Django 3.1 on 2025-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderplaced_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
